### ISSUE TITLE
Error message in Jupyter

### ISSUE THREAD

**Issue by vladrag** [Cledersonbc/tic-tac-toe-minimax#1]
clean()
    print(f'Computer turn [{c_choice}]')
    render(board, c_choice, h_choice)
    if depth == 9:
        x = choice([0, 1, 2])
        y = choice([0, 1, 2])
    else:
        move = minimax(board, depth, COMP)
        x, y = move[0], move[1]
    set_move(x, y, COMP)
    time.sleep(1)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-c6f983771815> in <module>
      1 clean()
----> 2 print(f'Computer turn [{c_choice}]')
      3 render(board, c_choice, h_choice)
      4 if depth == 9:
      5     x = choice([0, 1, 2])

NameError: name 'c_choice' is not defined

**Comment by Cledersonbc** [comment]
> ```
> clean()
> print(f'Computer turn [{c_choice}]')
> render(board, c_choice, h_choice)
> if depth == 9:
>     x = choice([0, 1, 2])
>     y = choice([0, 1, 2])
> else:
>     move = minimax(board, depth, COMP)
>     x, y = move[0], move[1]
> set_move(x, y, COMP)
> time.sleep(1)
> ```
> 
> NameError Traceback (most recent call last)
> in 
> 1 clean()
> ----> 2 print(f'Computer turn [{c_choice}]')
> 3 render(board, c_choice, h_choice)
> 4 if depth == 9:
> 5 x = choice([0, 1, 2])
> 
> NameError: name 'c_choice' is not defined

Hi, can you explain me step-by-step how do you get that exception? 'cause I need more information:

- Python version
- Jupyter Notebook version

**Comment by Cledersonbc** [comment]
This is not a valid issue. Pls, open a new issue with more information as needed.
